jupyterhub:
    hub:
        services:
            otter_grade:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:nd/Wo8BwgcemcfalCIFH8hluhVeVjA+uGPyT2xx94Y1v4u94ZiiqxBm0n1QUvEBJPyEmluzVOJ1GQI6yzStHQw==,iv:vOTHTOyyrR47zGViiGxZPCKM4zF5s9Q8iwMvCxDKoBE=,tag:8PTmCwtuvWlfz9DfVGdfBQ==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:xsUSJTsDTPkV7V8tNOypGIlPWhcrgpV5SKb0XVpgyqlrmlQJuL+07g17bShHi3155dRASOUC1ctF3KuGholbkw==,iv:rCK3wnec55EtdyMSec90GEeHPP/EggUupwLQSZQwO0M=,tag:LptyzpILqPLyPn4vXbEjIw==,type:str]
                api_token: ENC[AES256_GCM,data:9bEjuTA92gGEAFgAxmc5Jp978zH0yxuvV4izOHS2yys=,iv:gEb+Potqt3Z+dcAJyph7lRPjyKskVtUYgnp5UciZF88=,tag:xrOuhmFJb5YUposPrkGU5A==,type:str]
        config:
            LTI11Authenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:psmIe0RatbQHY7t621V1vYjRBohMzatep3orUIul+Q1H8xV5mMWVWnxb/yRZ+Suyw1CI4ZX4NBK0yYMo4Fvjdg==,iv:2zbsSczKvy4trEJb0JWmgEMsQt/e/4snGr0nfeSd8aI=,tag:7bTVu7+pjqz/HmQ2uO/5jg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2023-12-19T22:18:38Z"
          enc: CiUA67O9AALSos/bA5bHEEiM7NMz2B3CIyERJflaNebjshdfCNJfEkkAv/uvKnT9nDmNgt6DKSsaD/zjGvdBNMwK1zyafFnVvFN/DP2Jimyk0EWv4tT/ukTZ9imlFMsYXcJkZM2gUNu+RcKItQffsQqt
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-19T22:18:39Z"
    mac: ENC[AES256_GCM,data:+3bnYafIYH1GKvLBCannO2WQfzQnQPKOF6lStiCzBi6nV4QJ1X9T+GdeYFIz22WQhQN5Usin0RpTWZB1YHW4Em9zAmUbMj7Mq9wwlgSvIUK3eaEKu5CVygnPsSCt8OZTu8x+k2HzhOQjrYUnU3mglXIXKh+FWDQTV3v3FZW1qN8=,iv:0ZG/G1iUl+kcBLcj1IbJ2lUHYj1nvSGp522lYp2AQ5Q=,tag:xw6VEbsnDkbb1elxf0ef5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
