jupyterhub:
    hub:
        services:
            otter_grade:
                environment:
                    LTI_CONSUMER_KEY: ENC[AES256_GCM,data:GFpteMc1DMsjHaBCeCdX4D8pbx0R1a20BrVbPAr0aCkqHE6t7mC+edbKKSKM67zIelcndP2p/M7qx4dOr7qLxg==,iv:Dz+OY9bgd6dJX70z366jjbuZVreXo2KcFVhh8HLR+MQ=,tag:uueDceHvyczF797GcX7U4Q==,type:str]
                    LTI_CONSUMER_SECRET: ENC[AES256_GCM,data:w5Q9ws7B40tNbSwG/wW8sNeiymgvbGbp8BsqYWvoBrZa2nuzRYnTbhCmxaHQ3hM9iwrCkgodWSUHMSAAnb01ZA==,iv:BzNUpgwOKyeXXRo9dfLodK95TDounhOrPjk3Uqt6AeM=,tag:gsKF41l8JWLmRfnoZZUrng==,type:str]
                api_token: ENC[AES256_GCM,data:94Ur2RWAbgp//E9NkZELG5xv9oTm3sh2HDxVc2AMkNI=,iv:p5G7q4TzHYSy3AbeyTDS0VP3ngnzYx0lTps8rKvaXZ4=,tag:7fIsvwkwpd3tVcCxBob14A==,type:str]
        config:
            LTI11Authenticator:
                consumers:
                    b34eeb75dca9b467b1e074fb3eaeed4717a6aefd28d5e7e2c8c633fb016b2f39: ENC[AES256_GCM,data:J5lPOsUab3/wjoAd+tUNB9MicXdA1e8hwUXsgmmG3/c0bdH2kkRvpNP8UES2gCfB0x5m67520mZF/FhoXX0eGA==,iv:YFn6TARh+p8d3VRFm5Ul9PLvhgoIje6ZwYBJriIzzgg=,tag:sJitbF6Sglw3A+Qv3FHQtw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2023-12-19T21:53:52Z"
          enc: CiUA67O9ADZVKUl0ZuLF9VAOu9NqlluEPge/fhKTxNegSmnoyEJlEkkAv/uvKuZ22ZI7hyu/w/mjVVL6/0EbbKXin58IhKzp8MwtrFxHC9BSzuCIRUJPpiLNJZIKDZ2GlCHvxqh92fiEE2I0wPZb2wG3
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-19T21:53:52Z"
    mac: ENC[AES256_GCM,data:gP7fVn7LUz6P+oB3K1fM5dDwppjNqPBZZ5EyX/zdfBfded+D8Pt78r+sLTuQFCJcYvB5akbs0l3JdDMwzjxMjqvAdS/hP4RlTlTes/3JvbksHEF07M241d2pav5UH+EMxzqZ91pRWbHxMj/ltdNyhT/523dOc+BJxsplorju4DI=,iv:iBxV6JkaT03a/lNjq/4kjpERccx0PqGdXsFDisKhjck=,tag:AFt/FkiLYpMhJJuzicvLgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
